name: "CI"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  pre-build-tasks:
    name: Pre-Build Tasks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tasks: [lint, tsc]
    steps:
      - name: Checking out changes
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: "Running: ${{ matrix.tasks }}"
        run: pnpm ${{ matrix.tasks }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: pre-build-tasks
    steps:
      - name: Checking out changes
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Building Package
        run: pnpm build